### ISSUE TITLE
feature: Add support for cuda implicit types

### ISSUE THREAD

**Issue by Ergus** [theHamsta/tree-sitter-cuda#67]
### Did you check the tree-sitter docs?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

Some cuda keywords are not recognized properly (I am trying to create an emacs backend) 

### Describe the solution you'd like

There is not any inclusion for the implicit cuda types in the grammar like:

```
"dim3"
     "char1" "uchar1" "char2" "uchar2" "char3" "uchar3" "char4" "uchar4"
     "short1" "ushort1" "short2" "ushort2" "short3" "ushort3" "short4" "ushort4"
     "int1" "uint1" "int2" "uint2" "int3" "uint3" "int4" "uint4"
     "long1" "ulong1" "long2" "ulong2" "long3" "ulong3" "long4" "ulong4"
     "float1" "float2"  "float3" "float4"
     "double1" "double2"
``` 

Adding this may be pretty simple to do.

At the same time there are well defined cuda intrinsic patters that could be included.. this is an extra, but good to mention (as they don't seem complicated either:

There are other type specifiers: `__managed__` `__restrict__`

Some very common intrinsics:
- `__syncthreads`,
- `atomic{Add,And,CAS, Dec,Exch,...}`
- `__shfl_{up,down,xor}_sync`
- `__[a-z]+_sync`
- "__is{Global,Shared,Constant,GridConstant,Local}"

And Primary expressions really very useful in kernels:
- `gridDim` `blockIdx` `blockDim` `threadIdx` `warpSize`

**Comment by theHamsta** [comment]
I can add `__managed__` as this is probably required to parse the CUDA code correctly. But about the built-ins, what do you exactly want this grammar to provide? Do you want to have them highlighted? Hightlights should be done in the queries for your favorite editor.

**Comment by Ergus** [comment]
> I can add `__managed__` as this is probably required to parse the CUDA code correctly. But about the built-ins, what do you exactly want this grammar to provide? Do you want to have them highlighted? Hightlights should be done in the queries for your favorite editor.

Hi:

Actually the main concern are the types because Emacs handles those conceptually:

The definition is actually pretty simple; something like:

```
cuda_primitive_type: _ => token(choice(
	    'dim3',
	    ...[1, 2, 3, 4].map(n => `int${n}`),
	    ...[1, 2, 3, 4].map(n => `uint${n}`),
	    ...[1, 2, 3, 4].map(n => `short${n}`),
	    ...[1, 2, 3, 4].map(n => `ushort${n}`),
	    ...[1, 2, 3, 4].map(n => `long${n}`),
	    ...[1, 2, 3, 4].map(n => `ulong${n}`),
	    ...[1, 2, 3, 4].map(n => `char${n}`),
	    ...[1, 2, 3, 4].map(n => `uchar${n}`),
	    ...[1, 2, 3, 4].map(n => `float${n}`),
	    ...[1, 2].map(n => `double${n}`),
	))
```

And then just need to extend the `primitive_type` of c/c++ grammar to include those as well.

**Comment by ObserverOfTime** [comment]
Better yet:
```javascript
cuda_primitive_type: _ => token(choice(
  'dim3',
  /int[1-4]/,
  /uint[1-4]/,
  /short[1-4]/,
  /ushort[1-4]/,
  /long[1-4]/,
  /ulong[1-4]/,
  /char[1-4]/,
  /uchar[1-4]/,
  /float[1-4]/,
  /double[12]/,
))
```

**Comment by theHamsta** [comment]
But those are all valid tokens in C. Why build that into the parser? I only added modifiers that would otherwise destroy parsing of regular C++ code. Matching something like `dim3` or `float4` is something for the queries.
