### ISSUE TITLE
bug: no highlights.scm

### ISSUE THREAD

**Issue by viperML** [theHamsta/tree-sitter-cuda#91]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

The package.json reports a missing highlights.scm: https://github.com/tree-sitter-grammars/tree-sitter-cuda/blob/7c97acb8398734d790c86210c53c320df61ff66b/package.json#L57

### Steps To Reproduce/Bad Parse Tree

-

### Expected Behavior/Parse Tree

-

**Comment by theHamsta** [comment]
Thank you for reporting! I tried to add it in #93
