### ISSUE TITLE
New conflict from tree-sitter-cpp 0.23

### ISSUE THREAD

**Issue by alexaandru** [theHamsta/tree-sitter-cuda#99]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.23.0 (12fb31826b8469cc7b9788e72bceee5af1cf0977)

### Describe the bug

It compiled just fine until a few days ago (last time I compiled it was on Aug 29: https://github.com/alexaandru/go-sitter-forest/tree/main/cuda). After the recent change(s) it no longer compiles, but instead fails with:

```
$ npx tree-sitter generate --no-bindings
Unresolved conflict for symbol sequence:

  '__extension__'  expression  •  'kernel_call_syntax_token1'  …

Possible interpretations:

  1:  '__extension__'  (kernel_call_expression  expression  •  kernel_call_syntax  argument_list)
  2:  (extension_expression  '__extension__'  expression)  •  'kernel_call_syntax_token1'  …

Possible resolutions:

  1:  Specify a higher precedence in `kernel_call_expression` than in the other rules.
  2:  Specify a higher precedence in `extension_expression` than in the other rules.
  3:  Specify a left or right associativity in `extension_expression`
  4:  Add a conflict for these rules: `extension_expression`, `kernel_call_expression`
```

### Steps To Reproduce/Bad Parse Tree

1. `npx tree-sitter generate`
2. see it fail

### Expected Behavior/Parse Tree

Expected `generate` to work.

**Comment by clason** [comment]
Yes, this is due to a breaking change in the cpp grammar v0.23 that this grammar extends. It's not a crash, though; the grammar just has to be adapted to handle the new conflict.

**Comment by alexaandru** [comment]
I stand corrected, it's not a crash, updated the issue accordingly.

**Comment by alexaandru** [comment]
It's back working now, thank you :-) Cheers!
